Rewritten download-backup in ruby.

diff --git a/backup/etc/symbiosis/backup.d/pre-backup.d/00-download-backup b/backup/etc/symbiosis/backup.d/pre-backup.d/00-download-backup
--- a/backup/etc/symbiosis/backup.d/pre-backup.d/00-download-backup
+++ b/backup/etc/symbiosis/backup.d/pre-backup.d/00-download-backup
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/usr/bin/ruby
 #
 # Overview
 # --------
@@ -30,90 +30,37 @@
 # --
 #
 
-
+require 'symbiosis/range'
 
 #
 #  Local backup directory.
 #
-src=/var/backups/
-
-
+src = "/var/backups/"
 
 #
-#  The remote rsync location might be hardwired.
+# Automatically determine the primary backup space
 #
-#
-if [ -e /etc/symbiosis/dns.d/backup.name ]; then
-
-    #
-    #  If the file is empty then we just abort.
-    #
-    if [ ! -s /etc/symbiosis/dns.d/backup.name ]; then
-        exit 0;
-    fi
-
-    #
-    #  Otherwise we can rsync immediately from the specified location
-    #
-    rsync -vazr $(cat /etc/symbiosis/dns.d/backup.name)/localhost/ /var/backups/localhost/
-    exit 0;
-fi
-
-
-
-
-###
-##
-#
-#  OK we don't have an explicit name specified, so we need to look it up
-# dynamically.
-#
-##
-###
-
-
-
-#
-#  Find the IP address associated with eth0.
-#
-eth0=$(/sbin/ifconfig eth0 | grep 'inet addr:' | awk '{print $2}' | awk -F: '{print $2}' )
-
-
-
-#
-#  We need the IP reversed on an octet-basis for the DNS lookup.
-#
-one=$(echo $eth0   | awk -F\. '{print $1}')
-two=$(echo $eth0   | awk -F\. '{print $2}')
-three=$(echo $eth0 | awk -F\. '{print $3}')
-four=$(echo $eth0  | awk -F\. '{print $4}')
-
-
-
-#
-#  Attempt to find the name of the associated backup space via a
-# DNS lookup.
-#
-name=$(dig txt  $four.$three.$two.$one.backup-reverse.bytemark.co.uk +short | tr -d \")
-
-
+name = Symbiosis::Range.primary_backup_space.to_s
 
 #
 #  If we didn't get a name then exit.
 #
-if [ -z "$name" ]; then
-    echo "Failed to determine backup space name for $eth0"
-    exit 0
-fi
-
+if name.empty?
+  puts "Failed to determine backup space name.  Not downloading existing backups."
+  exit 0
+end
 
 #
-#  OK we got a name of the form "foo.backup.bytemark.co.uk"
+#  If we got a name of the form "foo.backup.bytemark.co.uk" truncate at the
+#  first part.  Otherwise use the name untouched.
 #
-#  Truncate at the first part.
-#
-name=$(echo $name | awk -F\. '{print $1}' )
-
+if name =~ /\.backup\.bytemark\.co\.uk$/
+  # Grab the FQDN
+  fqdn = `hostname --fqdn`
+  dest = name+"::"+name.split(".").first+"/"+fqdn
+else
+  dest = name
+end
 
 #
 #  Now rsync.
@@ -123,5 +70,9 @@ name=$(echo $name | awk -F\. '{print $1}' )
 #
 #    example.backup.bytemark.co.uk::example/example.vm.bytemark.co.uk/
 #
-rsync -vazr $name.backup.bytemark.co.uk::$name/$(hostname --fqdn)/localhost/ /var/backups/localhost/
-exit 0
+`rsync -vazr #{dest}/localhost/ #{src}/localhost/`
+
+#
+# Exit with the exit status of the rsync command
+#
+exit $?.exitstatus
