common: Updated SSL makefile to generate CSRs

diff --git a/common/ssl/Makefile b/common/ssl/Makefile
--- a/common/ssl/Makefile
+++ b/common/ssl/Makefile
@@ -1,6 +1,12 @@
 #!/usr/bin/make -f
 
 HOSTNAME ?= $(shell hostname -f)
+DAYS     ?= 3650
+
+ifneq "$(HOSTNAME)" ""
+SUBJECT  ?= /C=GB/ST=England/L=York/CN=$(HOSTNAME)
+endif
+
 tempext  := symbiosis.$(shell echo $$$$)
 
 check: check_crt check_combined
@@ -35,20 +41,32 @@ check_crt: ssl.crt ssl.key
 		echo "W: The key in ssl.key does not match the certificate in ssl.crt." ; \
 	fi
 
-ssl.crt:
-	@if [ -z "$(HOSTNAME)" ]  ; then \
-		echo "W: Could not determine hostname"; \
+ssl.csr: ssl.key
+	@if [ -z "$(SUBJECT)" ]  ; then \
+		echo "E: Could not determine certificate subject"; \
 		exit 1 ; \
 	fi
-	@openssl req -subj "/C=GB/ST=England/L=York/CN=$(HOSTNAME)" -new \
-		-x509 -days 3650 -nodes -out ssl.crt.$(tempext) -newkey rsa:2048 \
-		-keyout ssl.key.$(tempext) -sha256 > /dev/null
-	@mv -b ssl.crt.$(tempext) ssl.crt
-	@mv -b ssl.key.$(tempext) ssl.key
-	@echo "I: Created a self-signed certificate and key."
+	@openssl req -subj "$(SUBJECT)" -new \
+    -days $(DAYS) -key ssl.key -out ssl.csr.$(tempext) -sha256 > /dev/null
+	@mv -b ssl.csr.$(tempext) ssl.csr
+	@echo "I: Created a certifcate request."
 
-ssl.key: ssl.crt
+ssl.crt: ssl.key
+	@if [ -z "$(SUBJECT)" ]  ; then \
+		echo "E: Could not determine certificate subject"; \
+		exit 1 ; \
+	fi
+	@openssl req -subj "$(SUBJECT)" -new \
+		-x509 -days 3650 -nodes -out ssl.crt.$(tempext) \
+		-key ssl.key -sha256 > /dev/null
+	@mv -b ssl.crt.$(tempext) ssl.crt
+	@echo "I: Created a self-signed certificate."
+
+ssl.key: 
+	@openssl genrsa -out ssl.key.$(tempext) 2048
+	@mv -b ssl.key.$(tempext) ssl.key
 	@chmod 600 ssl.key
+	@echo "I: Created a key."
 
 ssl.combined: ssl.crt ssl.key 
 	@cp ssl.crt ssl.combined.$(tempext)
@@ -64,7 +82,21 @@ ssl.combined: ssl.crt ssl.key
 	@chmod 600 ssl.combined
 	@echo "I: Created combined certificate, bundle, and key."
 
+csr: ssl.csr
+req: csr
+request: csr
+
+crt: ssl.crt
+cert: crt
+certificate: crt
+self-signed-cert: crt
+self-signed-certificate: crt
+
+key: ssl.key
+
+combined: ssl.combined
+
 clean:
 	@$(RM) -v ssl.crt.symbiosis.[0-9]* ssl.key.symbiosis.[0-9]* ssl.combined.symbiosis.[0-9]* 
 
-.PHONY: clean check_crt check_combined check
+.PHONY: clean check_crt check_combined check crt cert certifcate self-signed-cert self-signed-certifcate csr req request key combined
